"""
Saleha Workflow Engine: Declarative Pythonic DSL (Workflow-as-Code).

Eliminates n8n's git-hostile 10,000-line JSON blobs by allowing developers to define
type-safe, version-controllable workflows directly in Python using decorators and fluent builders.
"""

from __future__ import annotations

import functools
import inspect
from typing import Any, Callable, Dict, List, Optional

from saleha.core.workflow.nodes import ActionNode, WorkflowExecutionContext, WorkflowNode
from saleha.core.workflow.self_healing_node import SelfHealingNode
from saleha.core.workflow.verified_sandbox_node import VerifiedSandboxNode
from saleha.core.workflow.bft_consensus_node import BFTConsensusNode
from saleha.core.workflow.workflow_engine import WorkflowDAG

# Global registry of declared workflows
_WORKFLOW_REGISTRY: Dict[str, WorkflowDAG] = {}


def register_workflow(dag: WorkflowDAG) -> None:
    _WORKFLOW_REGISTRY[dag.workflow_id] = dag
    _WORKFLOW_REGISTRY[dag.name] = dag


def get_workflow(name_or_id: str) -> Optional[WorkflowDAG]:
    return _WORKFLOW_REGISTRY.get(name_or_id)


def list_registered_workflows() -> List[WorkflowDAG]:
    seen: set = set()
    unique_list = []
    for dag in _WORKFLOW_REGISTRY.values():
        if dag.workflow_id not in seen:
            seen.add(dag.workflow_id)
            unique_list.append(dag)
    return unique_list


class WorkflowBuilder:
    """Fluent API for constructing workflows programmatically."""

    def __init__(self, name: str, description: str = "") -> None:
        self.dag = WorkflowDAG(name=name, description=description)

    def add_action(
        self,
        node_id: str,
        title: str,
        action_fn: Callable[[Dict[str, Any], WorkflowExecutionContext], Dict[str, Any]],
        depends_on: Optional[List[str]] = None,
        self_heal: bool = False,
    ) -> "WorkflowBuilder":
        base_node = ActionNode(node_id, title, action_fn=action_fn, depends_on=depends_on)
        if self_heal:
            self.dag.add_node(SelfHealingNode(base_node))
        else:
            self.dag.add_node(base_node)
        return self

    def add_sandbox_code(
        self,
        node_id: str,
        title: str,
        code_str: str,
        depends_on: Optional[List[str]] = None,
        verify_smt: bool = False,
        self_heal: bool = False,
    ) -> "WorkflowBuilder":
        base_node = VerifiedSandboxNode(
            node_id, title, code_str=code_str, verify_smt=verify_smt, depends_on=depends_on
        )
        if self_heal:
            self.dag.add_node(SelfHealingNode(base_node))
        else:
            self.dag.add_node(base_node)
        return self

    def add_bft_consensus(
        self,
        node_id: str,
        title: str,
        voters: List[Callable[[Dict[str, Any], WorkflowExecutionContext], str]],
        quorum_fraction: float = 0.66,
        depends_on: Optional[List[str]] = None,
    ) -> "WorkflowBuilder":
        node = BFTConsensusNode(
            node_id, title, voters=voters, quorum_fraction=quorum_fraction, depends_on=depends_on
        )
        self.dag.add_node(node)
        return self

    def connect(self, source_id: str, target_id: str) -> "WorkflowBuilder":
        self.dag.connect(source_id, target_id)
        return self

    def build(self, register: bool = True) -> WorkflowDAG:
        if register:
            register_workflow(self.dag)
        return self.dag


# Decorator syntax
_CURRENT_WORKFLOW_BUILDER: Optional[WorkflowBuilder] = None


def workflow(name: str, description: str = ""):
    """Decorator to declare a workflow module or class."""
    def decorator(cls_or_fn: Any) -> Any:
        dag = WorkflowDAG(name=name, description=description)
        # Extract steps defined on the class or generated by function
        if inspect.isclass(cls_or_fn):
            instance = cls_or_fn()
            for attr_name in dir(instance):
                attr = getattr(instance, attr_name)
                if hasattr(attr, "_is_workflow_step"):
                    node = attr._workflow_node
                    dag.add_node(node)
        register_workflow(dag)
        cls_or_fn._workflow_dag = dag
        return cls_or_fn
    return decorator


def step(
    depends_on: Optional[List[str]] = None,
    self_heal: bool = False,
    title: Optional[str] = None,
):
    """Decorator to define a step within a workflow."""
    def decorator(fn: Callable):
        node_id = fn.__name__
        node_title = title or node_id.replace("_", " ").title()

        def action_wrapper(inputs: Dict[str, Any], ctx: WorkflowExecutionContext) -> Dict[str, Any]:
            # Inspect parameter count
            sig = inspect.signature(fn)
            params = sig.parameters
            if len(params) == 2:
                res = fn(inputs, ctx)
            elif len(params) == 1:
                res = fn(inputs)
            else:
                res = fn()

            if isinstance(res, dict):
                return res
            return {"result": res}

        base_node = ActionNode(node_id, node_title, action_fn=action_wrapper, depends_on=depends_on)
        final_node = SelfHealingNode(base_node) if self_heal else base_node

        @functools.wraps(fn)
        def wrapper(*args, **kwargs):
            return fn(*args, **kwargs)

        wrapper._is_workflow_step = True  # type: ignore
        wrapper._workflow_node = final_node  # type: ignore
        return wrapper
    return decorator
