"""
Saleha Core: Concurrency checker -- static checks for Python race and deadlock
patterns that code generated by large models is measured to get wrong.

Why it exists: an independent review of Claude Opus 5.5 (the model that
wrote much of this repo) found concurrency findings rose 44% over its
previous version. Tests rarely catch these -- a race passes a test run
almost every time -- so this looks at the code itself.

Rules (each finding names the rule, line and why it matters):

  C001 unlocked-shared-write   a function started as a thread / pool task
                               writes module state or self.<attr> (+=, item
                               assignment, append...) outside any `with lock`
  C002 check-then-act          `if k not in shared: shared[k] = ...` in such
                               a function, outside a lock
  C003 acquire-without-release `x.acquire()` with no `x.release()` in a
                               finally block of the same function
  C004 lock-order-inversion    two functions take the same two locks in
                               opposite nesting order (deadlock risk)
  C005 blocking-in-async       time.sleep / requests.* / subprocess.run /
                               open(...).read inside `async def`
  C006 dropped-task            asyncio.create_task / ensure_future whose
                               result is discarded (can be garbage-collected)

Limits, stated: this is pattern matching on one file at a time. It does not
prove code race-free, it cannot see a lock held by a caller, and thread
targets are found only when started in the same file. It reports
`analyzed` / `skipped` so a partial scan never reads as a clean one.
"""

from __future__ import annotations

import ast
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Set, Tuple

_BLOCKING_CALLS = {
    ("time", "sleep"), ("requests", "get"), ("requests", "post"), ("requests", "put"),
    ("requests", "delete"), ("requests", "request"), ("subprocess", "run"),
    ("subprocess", "call"), ("subprocess", "check_output"), ("urllib.request", "urlopen"),
}
_MUTATING_METHODS = {"append", "extend", "insert", "pop", "remove", "clear", "update",
                     "add", "discard", "setdefault", "popitem"}


@dataclass
class Finding:
    rule: str
    path: str
    line: int
    message: str


@dataclass
class ConcurrencyReport:
    findings: List[Finding] = field(default_factory=list)
    analyzed: List[str] = field(default_factory=list)
    skipped: Dict[str, str] = field(default_factory=dict)

    @property
    def is_complete(self) -> bool:
        return not self.skipped


def _dotted(node: ast.AST) -> str:
    parts: List[str] = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
    return ".".join(reversed(parts))


def _walk_own(fn: ast.AST) -> Iterable[ast.AST]:
    """ast.walk over one function body, not descending into nested defs.

    Code in a nested def runs wherever that def is called -- e.g. inside
    asyncio.to_thread -- so blocking calls there are not blocking the loop.
    """
    stack = list(ast.iter_child_nodes(fn))
    while stack:
        node = stack.pop()
        yield node
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.Lambda)):
            stack.extend(ast.iter_child_nodes(node))


def _touched_elsewhere(tree: ast.Module, root: str, owner: ast.AST) -> bool:
    """Is `root` ("name" or "self.attr") used by any other function?

    A value only ever touched by the thread that owns it is not shared: this
    keeps C001 from flagging a poll loop's private bookkeeping.
    """
    attr = root[5:] if root.startswith("self.") else None
    for fn in ast.walk(tree):
        if fn is owner or not isinstance(fn, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if fn.name == "__init__" and attr:
            continue
        for node in ast.walk(fn):
            if attr and isinstance(node, ast.Attribute) and node.attr == attr                     and isinstance(node.value, ast.Name) and node.value.id == "self":
                return True
            if not attr and isinstance(node, ast.Name) and node.id == root:
                return True
    return False


def _thread_targets(tree: ast.AST) -> Set[str]:
    """Names of functions this file starts concurrently."""
    targets: Set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        callee = _dotted(node.func)
        if callee.endswith("Thread") or callee.endswith("Process"):
            for kw in node.keywords:
                if kw.arg == "target":
                    targets.add(_dotted(kw.value).split(".")[-1])
        # executor.submit(f) / pool.map(f) -- also on an unnamed executor,
        # `ThreadPoolExecutor().submit(f)`, whose dotted name is just
        # "submit". The builtin map(f, xs) is a Name call and stays out.
        elif node.args and (
                (isinstance(node.func, ast.Attribute) and node.func.attr in ("submit", "map"))
                or callee.endswith("start_new_thread")):
            targets.add(_dotted(node.args[0]).split(".")[-1])
    targets.discard("")
    return targets


def _module_names(tree: ast.Module) -> Set[str]:
    names: Set[str] = set()
    for node in tree.body:
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            for t in (node.targets if isinstance(node, ast.Assign) else [node.target]):
                if isinstance(t, ast.Name):
                    names.add(t.id)
    return names


def _is_lock_ctx(item: ast.withitem) -> bool:
    expr = item.context_expr
    name = _dotted(expr.func if isinstance(expr, ast.Call) else expr).lower()
    return any(w in name for w in ("lock", "mutex", "semaphore", "condition", "_cv"))


class _FunctionScan(ast.NodeVisitor):
    """Walks one function body, tracking whether we are inside `with lock`."""

    def __init__(self, shared: Set[str]) -> None:
        self.shared = shared
        self.lock_depth = 0
        self.writes: List[Tuple[int, str]] = []
        self.check_then_act: List[int] = []

    def _shared_root(self, target: ast.AST) -> Optional[str]:
        base = target
        while isinstance(base, (ast.Subscript, ast.Attribute)):
            if isinstance(base, ast.Attribute) and isinstance(base.value, ast.Name) and base.value.id == "self":
                return f"self.{base.attr}"
            base = base.value
        if isinstance(base, ast.Name) and base.id in self.shared:
            return base.id
        return None

    def visit_With(self, node: ast.With) -> None:
        locked = any(_is_lock_ctx(i) for i in node.items)
        self.lock_depth += locked
        self.generic_visit(node)
        self.lock_depth -= locked

    visit_AsyncWith = visit_With  # type: ignore[assignment]

    def _record(self, line: int, root: Optional[str]) -> None:
        if root and self.lock_depth == 0:
            self.writes.append((line, root))

    def visit_AugAssign(self, node: ast.AugAssign) -> None:
        self._record(node.lineno, self._shared_root(node.target))
        self.generic_visit(node)

    def visit_Assign(self, node: ast.Assign) -> None:
        for t in node.targets:
            if isinstance(t, (ast.Subscript, ast.Attribute)):
                self._record(node.lineno, self._shared_root(t))
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        if isinstance(node.func, ast.Attribute) and node.func.attr in _MUTATING_METHODS:
            self._record(node.lineno, self._shared_root(node.func.value))
        self.generic_visit(node)

    def visit_If(self, node: ast.If) -> None:
        test = node.test
        writes_item = any(isinstance(n, ast.Assign) and any(isinstance(t, ast.Subscript) for t in n.targets)
                          for n in ast.walk(ast.Module(body=node.body, type_ignores=[])))
        if (self.lock_depth == 0 and writes_item and isinstance(test, ast.Compare)
                and len(test.ops) == 1 and isinstance(test.ops[0], ast.NotIn)
                and self._shared_root(test.comparators[0])):
            self.check_then_act.append(node.lineno)
        self.generic_visit(node)

    # Nested defs are scanned on their own.
    def visit_FunctionDef(self, _node: ast.FunctionDef) -> None:
        return

    visit_AsyncFunctionDef = visit_FunctionDef  # type: ignore[assignment]


def _lock_orders(fn: ast.AST) -> List[Tuple[str, str, int]]:
    """(outer, inner, line) for every lock taken while another is held."""
    pairs: List[Tuple[str, str, int]] = []

    def walk(node: ast.AST, held: List[str]) -> None:
        for child in ast.iter_child_nodes(node):
            if isinstance(child, (ast.With, ast.AsyncWith)):
                names = [_dotted(i.context_expr) for i in child.items if _is_lock_ctx(i)]
                for n in names:
                    for h in held:
                        if h != n:
                            pairs.append((h, n, child.lineno))
                walk(child, held + names)
            elif not isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                walk(child, held)

    walk(fn, [])
    return pairs


def check_source(source: str, path: str = "<string>") -> List[Finding]:
    tree = ast.parse(source)
    findings: List[Finding] = []
    shared = _module_names(tree)
    targets = _thread_targets(tree)
    functions = [n for n in ast.walk(tree) if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))]

    orders: Dict[Tuple[str, str], Tuple[str, int]] = {}
    for fn in functions:
        if fn.name in targets:
            # A local (or parameter) that shadows a module name is not shared,
            # unless the function declares it `global`.
            declared = {n for node in ast.walk(fn) if isinstance(node, ast.Global) for n in node.names}
            local = {a.arg for a in fn.args.args + fn.args.kwonlyargs}
            for node in ast.walk(fn):
                if isinstance(node, ast.Name) and isinstance(node.ctx, ast.Store):
                    local.add(node.id)
            scan = _FunctionScan((shared - local) | (declared & shared))
            for stmt in fn.body:
                scan.visit(stmt)
            for line, root in scan.writes:
                if not _touched_elsewhere(tree, root, fn):
                    continue
                findings.append(Finding("C001", path, line,
                                        f"'{fn.name}' runs concurrently and writes '{root}' without a lock"))
            for line in scan.check_then_act:
                findings.append(Finding("C002", path, line,
                                        f"check-then-act on shared state in concurrent '{fn.name}': "
                                        "another thread can insert between the check and the write"))

        acquired: Dict[str, int] = {}
        released_in_finally: Set[str] = set()
        for node in ast.walk(fn):
            if (isinstance(node, ast.Call) and isinstance(node.func, ast.Attribute)
                    and node.func.attr == "acquire"):
                acquired.setdefault(_dotted(node.func.value), node.lineno)
            if isinstance(node, ast.Try):
                for stmt in node.finalbody:
                    for sub in ast.walk(stmt):
                        if (isinstance(sub, ast.Call) and isinstance(sub.func, ast.Attribute)
                                and sub.func.attr == "release"):
                            released_in_finally.add(_dotted(sub.func.value))
        for name, line in acquired.items():
            if name and name not in released_in_finally:
                findings.append(Finding("C003", path, line,
                                        f"'{name}.acquire()' has no release() in a finally block: "
                                        "an exception leaves it locked forever (use `with {name}:`)"))

        for outer, inner, line in _lock_orders(fn):
            reverse = orders.get((inner, outer))
            if reverse and reverse[0] != fn.name:
                findings.append(Finding("C004", path, line,
                                        f"'{fn.name}' takes {outer} then {inner}; '{reverse[0]}' "
                                        f"(line {reverse[1]}) takes them in the opposite order -- deadlock risk"))
            orders.setdefault((outer, inner), (fn.name, line))

        if isinstance(fn, ast.AsyncFunctionDef):
            for node in _walk_own(fn):
                if isinstance(node, ast.Call):
                    callee = _dotted(node.func)
                    mod, _, attr = callee.rpartition(".")
                    if (mod, attr) in _BLOCKING_CALLS:
                        findings.append(Finding("C005", path, node.lineno,
                                                f"blocking call {callee}() inside async '{fn.name}' "
                                                "stalls the whole event loop"))
                if isinstance(node, ast.Expr) and isinstance(node.value, ast.Call):
                    callee = _dotted(node.value.func)
                    if callee.endswith("create_task") or callee.endswith("ensure_future"):
                        findings.append(Finding("C006", path, node.lineno,
                                                f"result of {callee}() is dropped: the task can be "
                                                "garbage-collected mid-run; keep a reference"))
    return sorted(findings, key=lambda f: (f.path, f.line, f.rule))


def check_paths(paths: Iterable[str]) -> ConcurrencyReport:
    report = ConcurrencyReport()
    files: List[Path] = []
    for raw in paths:
        p = Path(raw)
        files += sorted(p.rglob("*.py")) if p.is_dir() else [p]
    for f in files:
        try:
            src = f.read_text(encoding="utf-8", errors="replace")
            report.findings += check_source(src, str(f))
            report.analyzed.append(str(f))
        except (OSError, SyntaxError, ValueError) as exc:
            report.skipped[str(f)] = f"{type(exc).__name__}: {exc}"
    return report
