# k8s/helm/mukti/templates/pdb.yaml
{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mukti.fullname" . }}
  labels:
    {{- include "mukti.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "mukti.selectorLabels" . | nindent 6 }}
{{- end }}
