export const HYPERBOLIC_DIM = 16;
export const CURVATURE_C = 1.0;
export const EPSILON_BOUNDARY = 0.9999;

export enum AgentDepartment {
  FOUNDATION_REASONING = 'FOUNDATION_REASONING',
  GENAI_MULTIMODAL = 'GENAI_MULTIMODAL',
  AGENTIC_SWARMS = 'AGENTIC_SWARMS',
  ADVANCED_RAG = 'ADVANCED_RAG',
  SYSTEMS_KERNEL = 'SYSTEMS_KERNEL',
  AIOPS_INFRA = 'AIOPS_INFRA',
  SECURITY_GOVERNANCE = 'SECURITY_GOVERNANCE',
  PHYSICAL_ROBOTICS = 'PHYSICAL_ROBOTICS',
  QUANTUM_PHYSICS = 'QUANTUM_PHYSICS',
  ENTERPRISE_AI = 'ENTERPRISE_AI',
}
