"""
Saleha Agents: UI/UX Designer Agent

Creates cohesive UI design systems, token palettes, typography scales,
component hierarchies, modern glassmorphism aesthetics, and micro-interactions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any

from saleha.agents.base_agent import BaseAgent, AgentResponse


@dataclass
class DesignSystemSpec:
    theme_name: str
    color_palette: Dict[str, str]
    typography: Dict[str, str]
    components_css: str
    design_tokens_json: str
    model_used: str = ""


class DesignerAgent(BaseAgent):
    """Principal UI/UX Designer & Design System Architect Agent."""

    def __init__(self, model: str = "auto"):
        super().__init__(role="Designer", model=model)

    def create_design_system(
        self,
        project_goal: str,
        theme_style: str = "cyber_glassmorphism"
    ) -> DesignSystemSpec:
        """Synthesizes comprehensive CSS design tokens and component styling."""
        palette = {
            "bg_dark": "#030712",
            "bg_surface": "#0b0f19",
            "accent_primary": "#00f2fe",
            "accent_secondary": "#a855f7",
            "accent_success": "#10b981",
            "text_main": "#f8fafc",
            "text_muted": "#94a3b8",
            "border_subtle": "rgba(255, 255, 255, 0.08)"
        }

        typography = {
            "font_sans": "'Plus Jakarta Sans', -apple-system, sans-serif",
            "font_heading": "'Space Grotesk', sans-serif",
            "font_mono": "'Fira Code', monospace"
        }

        css_components = f"""/* ==========================================================================
   Design System: {theme_style.title()} for {project_goal}
   Generated by Saleha DesignerAgent
   ========================================================================== */

:root {{
  --bg-dark: {palette['bg_dark']};
  --bg-surface: {palette['bg_surface']};
  --accent-cyan: {palette['accent_primary']};
  --accent-purple: {palette['accent_secondary']};
  --accent-emerald: {palette['accent_success']};
  --text-main: {palette['text_main']};
  --text-muted: {palette['text_muted']};
  --border-subtle: {palette['border_subtle']};
}}

.glass-card {{
  background: rgba(17, 24, 39, 0.7);
  backdrop-filter: blur(16px);
  -webkit-backdrop-filter: blur(16px);
  border: 1px solid var(--border-subtle);
  border-radius: 16px;
  padding: 24px;
  transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
}}

.glass-card:hover {{
  border-color: rgba(0, 242, 254, 0.4);
  transform: translateY(-4px);
  box-shadow: 0 15px 35px rgba(0, 242, 254, 0.15);
}}

.btn-glow-primary {{
  background: linear-gradient(135deg, var(--accent-cyan), var(--accent-purple));
  color: #000;
  font-weight: 700;
  border-radius: 12px;
  padding: 12px 24px;
  border: none;
  cursor: pointer;
  box-shadow: 0 0 25px rgba(0, 242, 254, 0.35);
  transition: all 0.2s ease;
}}

.btn-glow-primary:hover {{
  transform: scale(1.03);
  box-shadow: 0 0 35px rgba(0, 242, 254, 0.55);
}}
"""

        tokens_json = """{
  "theme": "dark",
  "radius": "16px",
  "blur": "16px",
  "animation": "300ms cubic-bezier(0.16, 1, 0.3, 1)"
}"""

        return DesignSystemSpec(
            theme_name=theme_style,
            color_palette=palette,
            typography=typography,
            components_css=css_components,
            design_tokens_json=tokens_json,
            model_used=self.model_preference
        )
