"""
Saleha Agents: Autonomous Codebase Architecture & Documentation Generator (DocGeneratorAgent)

Scans software repositories, parses AST symbols, and autonomously synthesizes:
1. System Architecture Overview with interactive Mermaid diagrams.
2. Complete Module and API Reference documentation.
3. High-level Component Hierarchy and Dataflow graphs.
"""

from __future__ import annotations

import os
import ast
import time
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional

from saleha.agents.base_agent import BaseAgent, AgentResponse


@dataclass
class CodebaseDocSpec:
    repo_name: str
    modules_found: List[str]
    total_classes: int
    total_functions: int
    architecture_diagram_mermaid: str
    api_reference_markdown: str
    full_doc_markdown: str
    generation_time_ms: float = 0.0


class DocGeneratorAgent(BaseAgent):
    """Autonomous Repository Architecture & API Documentation Synthesizer."""

    def __init__(self, role: str = "Documentation Specialist", model: str = "auto"):
        super().__init__(role=role, model=model)
        self.name = "DocGenerator"

    def scan_and_generate_docs(self, target_dir: str = ".") -> CodebaseDocSpec:
        """Inspects directory, parses Python ASTs, and generates architectural markdown with Mermaid diagrams."""
        start_time = time.time()
        root = Path(target_dir)
        repo_name = root.resolve().name or "Saleha"

        modules: List[str] = []
        classes_found = 0
        functions_found = 0
        module_details: List[Dict[str, Any]] = []

        # Walk through python files (ignoring venv and git)
        for py_file in root.rglob("*.py"):
            rel_str = str(py_file.relative_to(root))
            if any(p in rel_str for p in [".git", "venv", "__pycache__", "node_modules", ".pytest_cache"]):
                continue

            modules.append(rel_str)
            try:
                tree = ast.parse(py_file.read_text(encoding="utf-8", errors="ignore"))
                cls_names = [n.name for n in ast.walk(tree) if isinstance(n, ast.ClassDef)]
                fn_names = [n.name for n in ast.walk(tree) if isinstance(n, ast.FunctionDef) and not n.name.startswith("_")]
                classes_found += len(cls_names)
                functions_found += len(fn_names)

                module_details.append({
                    "path": rel_str,
                    "classes": cls_names,
                    "functions": fn_names,
                    "docstring": ast.get_docstring(tree) or "No module docstring",
                })
            except Exception:
                continue

        # Synthesize a Mermaid diagram from the real scan.
        #
        # This used to be a hardcoded string ("19 First-Class Python Agents",
        # a fixed list of six named agent classes) that never varied with
        # the scanned directory -- confirmed against this repo directly:
        # saleha/agents/ has 28 real persona files, not 19, and the fixed
        # class list omitted more than half of them. The genuinely computed
        # module/class/function counts above it made the diagram next to
        # them look computed too. Now it lists the real top-level classes
        # found under any path containing "agents" (capped so the diagram
        # stays readable), falling back to a plain node when none are found
        # rather than inventing agent names.
        agent_classes: List[str] = []
        for mod in module_details:
            if "agents" in mod["path"].replace("\\", "/").split("/"):
                agent_classes.extend(mod["classes"])
        agent_node_lines = "\n".join(
            f'        Agents --> {name}["{name}"]' for name in agent_classes[:12]
        ) or '        Agents --> NoAgentsFound["(no classes found under agents/)"]'
        agent_count_label = f"{len(agent_classes)} Agent Classes Found" if agent_classes else "No Agent Classes Found"

        mermaid_diagram = f"""```mermaid
graph TD
    CLI[Saleha Unified CLI commands.py] --> Core[Saleha Core Engine]
    CLI --> Agents[{agent_count_label}]

    subgraph "Agents Ecosystem"
{agent_node_lines}
    end
```"""

        # Synthesize API Reference Markdown
        api_sections = []
        for mod in module_details[:10]:
            cls_str = ", ".join(f"`{c}`" for c in mod["classes"]) if mod["classes"] else "None"
            fn_str = ", ".join(f"`{f}()`" for f in mod["functions"][:5]) if mod["functions"] else "None"
            api_sections.append(f"### `{mod['path']}`\n- **Classes**: {cls_str}\n- **Functions**: {fn_str}\n")

        api_ref = "\n".join(api_sections)

        full_doc = f"""# {repo_name} Codebase Architecture & Technical Reference

Autonomously generated by Saleha's DocGeneratorAgent.

---

## Repository Metrics
- **Total Scanned Python Modules**: `{len(modules)}`
- **Total Classes Defined**: `{classes_found}`
- **Total Public Functions**: `{functions_found}`

---

## System Architecture Diagram
{mermaid_diagram}

---

## Key Module API Reference
{api_ref}

---
*Generated in `{round((time.time() - start_time)*1000, 2)}ms` by Saleha AI Documentation Engine.*
"""

        elapsed = round((time.time() - start_time) * 1000, 2)

        return CodebaseDocSpec(
            repo_name=repo_name,
            modules_found=modules,
            total_classes=classes_found,
            total_functions=functions_found,
            architecture_diagram_mermaid=mermaid_diagram,
            api_reference_markdown=api_ref,
            full_doc_markdown=full_doc,
            generation_time_ms=elapsed,
        )

    def execute(self, prompt: str, **kwargs) -> AgentResponse:
        spec = self.scan_and_generate_docs(prompt or ".")
        return AgentResponse(
            success=True,
            content=f"Generated documentation for {spec.repo_name} ({len(spec.modules_found)} modules, {spec.total_classes} classes) in {spec.generation_time_ms}ms.",
            model_used="DocGeneratorEngine",
            response_time=spec.generation_time_ms / 1000.0,
        )


doc_generator = DocGeneratorAgent()
