"""
Saleha Harness: Main Orchestration Engine

Dispatches benchmark tasks to parallel workers, has the orchestrator generate
code for each, runs the task's own tests against that code, and aggregates
Pass@1.

Three things this module once got wrong, each of which filled the leaderboard
with numbers nothing had measured:

- `dry_run` returned `passed=True` for every task and the report was saved to
  the persistent history -- 947 records, every one a 100% dry run, were the
  entire leaderboard. A dry run now only lists the tasks it would run; it has
  no score and is never saved.
- The pass marker was a fixed string, so candidate code that printed it and
  raised SystemExit(0) passed without a single assertion running. The marker
  now carries a per-run nonce the candidate never sees.
- A task whose tests never ran (memory replay, sandbox block, no code, harness
  error) is reported as not executed rather than folded into pass or fail.

And one that failed everything instead: the candidate's `__main__` guard
(see `saleha.core.harness.test_runner.strip_main_guard`).
"""

import secrets
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Dict, List, Optional

from saleha.core.harness.code_executor import CodeExecutor

# Shared with the orchestrator's test runner. The orchestrator's output ends
# with its own `unittest.main()` under a __main__ guard; run as a script it
# exited before the task's tests, so a correct `is_valid_parentheses` scored
# FAIL. Re-exported here for callers that use `saleha.harness.core.strip_main_guard`.
from saleha.core.harness.test_runner import strip_main_guard
from saleha.harness.benchmarks import BenchmarkCatalog, BenchmarkTaskSpec
from saleha.harness.metrics import HarnessTaskResult, compute_benchmark_summary, pass_rate
from saleha.harness.reporter import HarnessReport, reporter
from saleha.orchestrator import SalehaOrchestrator

__all__ = ["PASS_MARKER", "SalehaHarness", "harness", "strip_main_guard"]

PASS_MARKER = "HARNESS_TEST_PASSED"


class SalehaHarness:
    """Benchmark evaluation harness: one generated sample per task, scored by the task's tests."""

    def __init__(self):
        self.executor = CodeExecutor()

    def _evaluate_single_task(self, task: BenchmarkTaskSpec, model: str) -> HarnessTaskResult:
        start_t = time.time()

        def _not_run(reason: str, attempts: int = 0) -> HarnessTaskResult:
            return HarnessTaskResult(
                task_id=task.id,
                benchmark=task.benchmark,
                prompt=task.prompt,
                passed=False,
                attempts_used=attempts,
                latency_sec=round(time.time() - start_t, 2),
                error_detail=reason,
                executed=False,
            )

        try:
            orchestrator = SalehaOrchestrator(model=model, max_healing_attempts=2)
            orch_res = orchestrator.execute_task(task.prompt, use_memory=False)
        except Exception as e:
            return _not_run(f"harness error before tests ran: {type(e).__name__}: {e}")

        code = orch_res.final_code or ""
        # use_memory=False should prevent a replay; if one still comes back it
        # was not generated by `model` in this run and measures nothing about it.
        if getattr(orch_res, "profile_used", "") == "memory_store":
            return _not_run("replayed from memory store; the model was not called")
        if not code.strip():
            last_line = (orch_res.log or "").strip().splitlines()[-1:] or ["no log"]
            return _not_run(f"no code generated: {last_line[0][:200]}", orch_res.attempts)

        # The candidate code runs first in the same process, so it could print
        # a fixed marker and exit before any assertion ran. It never sees this
        # nonce, so only the task's own test code can print it.
        marker = f"{PASS_MARKER}_{secrets.token_hex(8)}"
        test_code = task.test_code.replace(PASS_MARKER, marker)
        if marker not in test_code:
            return _not_run(f"task {task.id} test code has no {PASS_MARKER} line")

        exec_res = self.executor.execute(f"{strip_main_guard(code)}\n\n{test_code}", timeout=task.timeout_sec)
        elapsed = round(time.time() - start_t, 2)
        if exec_res.blocked:
            return _not_run(f"blocked by sandbox before tests ran: {exec_res.block_reason or exec_res.error}",
                            orch_res.attempts)

        passed = exec_res.success and marker in exec_res.output
        return HarnessTaskResult(
            task_id=task.id,
            benchmark=task.benchmark,
            prompt=task.prompt,
            passed=passed,
            attempts_used=orch_res.attempts,
            latency_sec=elapsed,
            error_detail=None if passed else (exec_res.error or exec_res.output or "tests did not print the pass marker")[:500],
        )

    def evaluate(
        self,
        model: str = "auto",
        benchmark: str = "all",
        limit: Optional[int] = None,
        workers: int = 4,
        dry_run: bool = False
    ) -> HarnessReport:
        """
        Run the selected benchmarks and return the report.

        `dry_run` lists the selected tasks without generating or running
        anything; its report has no score and is not saved to history.
        Raises ValueError for an unknown benchmark or a limit below 1.
        """
        tasks = BenchmarkCatalog.get_benchmarks(benchmark)
        if not tasks:
            available = ", ".join(["all", *BenchmarkCatalog.list_available_benchmarks()])
            raise ValueError(f"unknown benchmark '{benchmark}' (available: {available})")
        if limit is not None:
            if limit < 1:
                raise ValueError(f"limit must be at least 1, got {limit}")
            tasks = tasks[:limit]

        timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
        if dry_run:
            planned: Dict[str, List[str]] = {}
            for t in tasks:
                planned.setdefault(t.benchmark, []).append(t.id)
            return HarnessReport(
                model_name=model,
                timestamp=timestamp,
                total_tasks=len(tasks),
                executed_tasks=0,
                passed_tasks=0,
                overall_pass_at_1=None,
                avg_latency_sec=0.0,
                dry_run=True,
                planned_tasks=planned,
            )

        results_by_suite: Dict[str, List[HarnessTaskResult]] = {}
        all_results: List[HarnessTaskResult] = []

        if workers <= 1:
            for task in tasks:
                res = self._evaluate_single_task(task, model)
                results_by_suite.setdefault(res.benchmark, []).append(res)
                all_results.append(res)
        else:
            with ThreadPoolExecutor(max_workers=min(workers, len(tasks))) as pool:
                futures = [pool.submit(self._evaluate_single_task, t, model) for t in tasks]
                for fut in as_completed(futures):
                    res = fut.result()
                    results_by_suite.setdefault(res.benchmark, []).append(res)
                    all_results.append(res)

        summaries = {name: compute_benchmark_summary(name, rs) for name, rs in results_by_suite.items()}

        executed = [r for r in all_results if r.executed]
        passed = sum(1 for r in executed if r.passed)
        avg_lat = round(sum(r.latency_sec for r in executed) / len(executed), 2) if executed else 0.0

        report = HarnessReport(
            model_name=model,
            timestamp=timestamp,
            total_tasks=len(all_results),
            executed_tasks=len(executed),
            passed_tasks=passed,
            overall_pass_at_1=pass_rate(passed, len(executed)),
            avg_latency_sec=avg_lat,
            benchmark_summaries=summaries,
        )

        # Nothing executed means nothing was measured; a leaderboard row for
        # it would rank a model on work that never happened.
        if report.executed_tasks > 0:
            report.saved = reporter.save_report(report)
        return report


# Global instance
harness = SalehaHarness()
