# k8s/monitoring/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mukti-servicemonitor
  namespace: mukti
  labels:
    app: mukti
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mukti
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
  namespaceSelector:
    matchNames:
      - mukti
