"""Keep Saleha's documents in step with its code, and version each of them.

Three mechanisms, none of which lets a model write a fact into the docs:

1. Generated regions. A doc marks a region with
   ``<!-- saleha:generated:NAME -->`` ... ``<!-- /saleha:generated:NAME -->``;
   ``sync`` re-renders it from the code (scanner rule catalog, governance
   controls, project version). ``docs/CLI_REFERENCE.md`` is generated whole.
2. Stale claims. Backticked ``saleha <command>`` mentions and repo paths are
   checked against the real CLI and filesystem, and reported with doc:line.
   They are reported, not rewritten: fixing prose needs judgment.
3. Document versions. ``docs/doc_versions.json`` records each managed doc's
   own SemVer and content hash; a doc whose content changed gets a patch bump
   and a ``doc-version`` stamp naming the Saleha version it describes.
"""

from __future__ import annotations

import datetime as _dt
import hashlib
import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional

REPO_ROOT = Path(__file__).resolve().parents[3]
MANIFEST_REL = "docs/doc_versions.json"
CLI_REFERENCE_REL = "docs/CLI_REFERENCE.md"

_REGION_RE = re.compile(
    r"(<!-- saleha:generated:(?P<name>[a-z0-9-]+) -->\n)(?P<body>.*?)(<!-- /saleha:generated:(?P=name) -->)",
    re.DOTALL,
)
_DOC_GLOBS = ("docs/*.md", "README.md", "SECURITY.md", "CONTRIBUTING.md")


# ---------------------------------------------------------------- regions

def extract_region(text: str, name: str) -> Optional[str]:
    for m in _REGION_RE.finditer(text):
        if m.group("name") == name:
            return m.group("body")
    return None


def _render_security_rules(root: Path) -> str:
    from saleha.core.verification.security_scanner import RULE_CATALOG
    lines = ["| Rule ID | Severity | Language | Detects | Remediation |", "|---|---|---|---|---|"]
    for rid in sorted(RULE_CATALOG):
        r = RULE_CATALOG[rid]
        lines.append(f"| `{rid}` | {r.severity} | {r.language} | {r.title} | {r.remediation} |")
    return "\n".join(lines) + "\n"


def _render_controls(root: Path) -> str:
    from saleha.core.governance.controls import CONTROLS, load_baseline
    baseline = load_baseline()
    lines = ["| Control | What it checks | Ratchet baseline |", "|---|---|---|"]
    metric_of = {
        "GOV-SAST-TESTS": "untested_scanner_rules",
        "GOV-SUBPROCESS-TIMEOUT": "subprocess_without_timeout",
        "GOV-SUBPROCESS-ENCODING": "subprocess_text_without_encoding",
        "GOV-SAST-SELF": "high_sast_findings",
        "GOV-DOCS-STALE": "stale_doc_claims",
    }
    for c in CONTROLS:
        metric = metric_of.get(c.control_id)
        base = "-" if metric is None else (
            f"`{metric}` <= {baseline[metric]}" if metric in baseline else f"`{metric}` (not recorded)")
        lines.append(f"| `{c.control_id}` | {c.checks} | {base} |")
    return "\n".join(lines) + "\n"


def _render_version(root: Path) -> str:
    from saleha.core.governance.versioning import read_project_version
    return f"Saleha version: **{read_project_version(root) or 'unknown'}**\n"


_RENDERERS = {
    "security-rules": _render_security_rules,
    "governance-controls": _render_controls,
    "project-version": _render_version,
}


def render_region(name: str, root: Path = REPO_ROOT) -> str:
    return _RENDERERS[name](root)


def render_cli_reference() -> str:
    """Full text of docs/CLI_REFERENCE.md, from the live Click command tree."""
    import click

    from saleha.cli.commands import cli

    def params(cmd: click.Command) -> str:
        parts = []
        for p in cmd.params:
            if isinstance(p, click.Argument):
                parts.append(f"`<{(p.name or '').upper()}>`")
            elif isinstance(p, click.Option):
                arg = "" if p.is_flag else f" `{(p.name or '').upper()}`"
                parts.append(f"`{'/'.join(p.opts)}{arg}`")
        return " ".join(parts) if parts else "-"

    def describe(cmd: click.Command) -> str:
        return (cmd.help or "").strip().splitlines()[0] if cmd.help else ""

    out = ["# Saleha CLI Reference", "",
           "> Auto-generated by `python scripts/gen_cli_docs.py`; regenerate instead of editing.", "",
           "## Commands\n", "### All Commands\n",
           "| Command | Description | Options |", "|---|---|---|"]
    for name in sorted(cli.commands):
        c = cli.commands[name]
        if not isinstance(c, click.Group):
            out.append(f"| `saleha {name}` | {describe(c)} | {params(c)} |")
    out.append("")
    for gname in sorted(cli.commands):
        sub = cli.commands[gname]
        if isinstance(sub, click.Group):
            out += [f"#### `saleha {gname}` group\n", "| Sub-command | Description | Options |", "|---|---|---|"]
            for sname in sorted(sub.commands):
                sc = sub.commands[sname]
                out.append(f"| `saleha {gname} {sname}` | {describe(sc)} | {params(sc)} |")
            out.append("")
    return "\n".join(out) + "\n"


# ---------------------------------------------------------------- versions

def _content_hash(text: str) -> str:
    """Hash of a doc without its own version stamp, so stamping is not a change."""
    stripped = _REGION_RE.sub(
        lambda m: "" if m.group("name") == "doc-version" else m.group(0), text)
    return hashlib.sha256(stripped.replace("\r\n", "\n").encode("utf-8")).hexdigest()


def _bump_patch(version: str) -> str:
    major, minor, patch = (int(x) for x in version.split("."))
    return f"{major}.{minor}.{patch + 1}"


def load_manifest(root: Path = REPO_ROOT) -> Dict[str, dict]:
    path = root / MANIFEST_REL
    if not path.is_file():
        return {}
    return json.loads(path.read_text(encoding="utf-8")).get("documents", {})


# ---------------------------------------------------------------- sync

@dataclass
class DocChange:
    path: str
    regions_changed: List[str] = field(default_factory=list)
    unknown_regions: List[str] = field(default_factory=list)
    old_version: Optional[str] = None
    new_version: Optional[str] = None
    content_changed: bool = False
    new_text: str = ""


def managed_docs(root: Path = REPO_ROOT) -> List[Path]:
    """Docs with at least one generated region, plus the CLI reference."""
    seen: Dict[str, Path] = {}
    for pattern in _DOC_GLOBS:
        for p in sorted(root.glob(pattern)):
            text = p.read_text(encoding="utf-8", errors="replace")
            if _REGION_RE.search(text) or p.as_posix().endswith(CLI_REFERENCE_REL):
                seen[p.relative_to(root).as_posix()] = p
    return [seen[k] for k in sorted(seen)]


def _render_regions(text: str, root: Path, change: DocChange) -> str:
    """Re-render every known region except the version stamp."""
    def _sub(m: "re.Match[str]") -> str:
        name = m.group("name")
        if name == "doc-version":
            return m.group(0)  # stamped once the new version is known
        if name not in _RENDERERS:
            change.unknown_regions.append(name)
            return m.group(0)
        body = render_region(name, root)
        if body != m.group("body"):
            change.regions_changed.append(name)
        return m.group(1) + body + m.group(4)
    return _REGION_RE.sub(_sub, text)


def _stamp(text: str, stamp: str) -> str:
    return _REGION_RE.sub(
        lambda m: (m.group(1) + stamp + m.group(4)) if m.group("name") == "doc-version" else m.group(0),
        text)


def plan_sync(root: Path = REPO_ROOT, today: Optional[str] = None) -> List[DocChange]:
    """What `sync --apply` would change. Pure: writes nothing."""
    from saleha.core.governance.versioning import read_project_version

    today = today or _dt.date.today().isoformat()
    project_version = read_project_version(root) or "unknown"
    manifest = load_manifest(root)
    changes: List[DocChange] = []
    for path in managed_docs(root):
        rel = path.relative_to(root).as_posix()
        old_text = path.read_text(encoding="utf-8").replace("\r\n", "\n")
        change = DocChange(path=rel)

        if rel == CLI_REFERENCE_REL:
            new_text = render_cli_reference()
            if new_text != old_text:
                change.regions_changed.append("(whole file)")
        else:
            new_text = _render_regions(old_text, root, change)

        entry = manifest.get(rel)
        new_hash = _content_hash(new_text)
        if entry is None:
            change.content_changed, change.new_version, updated = True, "1.0.0", today
        else:
            change.old_version = entry.get("version")
            change.content_changed = entry.get("sha256") != new_hash
            if change.content_changed:
                change.new_version, updated = _bump_patch(entry["version"]), today
            else:
                change.new_version, updated = entry["version"], entry.get("updated", today)

        change.new_text = _stamp(new_text, f"Document version {change.new_version} -- describes "
                                           f"Saleha {project_version} -- updated {updated}\n")
        changes.append(change)
    return changes

def apply_sync(changes: List[DocChange], root: Path = REPO_ROOT,
               today: Optional[str] = None) -> List[str]:
    """Write changed docs and the manifest. Returns the paths written."""
    from saleha.core.governance.versioning import read_project_version, write_preserving_eol

    today = today or _dt.date.today().isoformat()
    manifest = load_manifest(root)
    written: List[str] = []
    for ch in changes:
        path = root / ch.path
        if path.read_text(encoding="utf-8").replace("\r\n", "\n") != ch.new_text:
            write_preserving_eol(path, ch.new_text)
            written.append(ch.path)
        if ch.content_changed:
            manifest[ch.path] = {"version": ch.new_version, "sha256": _content_hash(ch.new_text),
                                 "saleha_version": read_project_version(root), "updated": today}
    manifest_path = root / MANIFEST_REL
    payload = json.dumps({"_comment": "Written by `saleha governance docs --apply`.",
                          "documents": dict(sorted(manifest.items()))}, indent=2) + "\n"
    old = manifest_path.read_text(encoding="utf-8").replace("\r\n", "\n") if manifest_path.is_file() else None
    if payload != old:
        write_preserving_eol(manifest_path, payload)
        written.append(MANIFEST_REL)
    return written


# ---------------------------------------------------------------- stale claims

@dataclass
class StaleClaim:
    doc: str
    line: int
    claim: str
    reason: str


_BACKTICK_RE = re.compile(r"`([^`\n]+)`")
_DATED_RE = re.compile(r"\d{4}-\d{2}-\d{2}")
_PATH_RE = re.compile(r"^[A-Za-z0-9_.\-]+(/[A-Za-z0-9_.\-]+)+/?$")
_EXTS = (".py", ".md", ".toml", ".json", ".yml", ".yaml", ".rs", ".ts", ".tsx", ".js", ".sh", ".txt", ".html")


def _cli_names() -> Dict[str, Optional[set]]:
    import click

    from saleha.cli.commands import cli
    names: Dict[str, Optional[set]] = {}
    for name, cmd in cli.commands.items():
        names[name] = set(cmd.commands) if isinstance(cmd, click.Group) else None
    return names


def find_stale_claims(root: Path = REPO_ROOT) -> List[StaleClaim]:
    """Backticked `saleha <cmd>` and repo paths in docs that do not exist."""
    commands = _cli_names()
    claims: List[StaleClaim] = []
    for pattern in _DOC_GLOBS:
        for doc in sorted(root.glob(pattern)):
            rel = doc.relative_to(root).as_posix()
            if _DATED_RE.search(doc.name):
                continue  # a dated review records the tree as it was that day
            in_fence = False
            for lineno, line in enumerate(doc.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
                if line.lstrip().startswith("```"):
                    in_fence = not in_fence
                    continue
                if in_fence:
                    continue
                for token in _BACKTICK_RE.findall(line):
                    token = token.strip()
                    reason = _check_command(token, commands) or _check_path(token, root, doc.parent)
                    if reason:
                        claims.append(StaleClaim(rel, lineno, token, reason))
    return claims


def _check_command(token: str, commands: Dict[str, Optional[set]]) -> Optional[str]:
    words = token.split()
    if len(words) < 2 or words[0] != "saleha" or words[1].startswith("-"):
        return None
    name = words[1]
    if not re.fullmatch(r"[a-z][a-z0-9-]*", name):
        return None  # placeholder such as <command>
    if name not in commands:
        return "no such CLI command"
    subs = commands[name]
    if (subs is not None and len(words) > 2 and re.fullmatch(r"[a-z][a-z0-9-]*", words[2])
            and words[2] not in subs):
        return f"no such `saleha {name}` sub-command"
    return None


def _check_path(token: str, root: Path, doc_dir: Path) -> Optional[str]:
    if not _PATH_RE.match(token) or "://" in token:
        return None
    if not (token.endswith("/") or token.endswith(_EXTS)):
        return None  # module paths, versions and the like
    if token.startswith(("~", "/")) or token.startswith(".saleha") or token.startswith(".ik"):
        return None  # user-home or runtime paths
    # Repo-relative, relative to the doc, or the saleha/core shorthand the
    # README uses ("rag/graph_rag.py").
    for base in (root, doc_dir, root / "saleha", root / "saleha" / "core"):
        if (base / token).exists():
            return None
    return "path does not exist"
