"""
Saleha Core Engine Package

Exports the multi-agent orchestrator suite via PEP 562 lazy loading:
- TreeOfThoughtsOrchestrator (State-Space Search & Self-Evolving Heuristics)
- CloudInfraOrchestrator (IaC, Kubernetes, FinOps, IAM)
- MultiRepoOrchestrator (Cross-Repo Sync & Correlated PRs)
- SiliconCircuitOrchestrator (Verilog / SystemVerilog RTL Synthesis)
- DebateConsensusOrchestrator (Game-Theoretic Multi-Agent Deliberation)
- TeamOrchestrator (5-Stage Polyglot Swarm Delivery)
- SwarmPipelineEngine & AutonomousSwarmRouter (Dynamic DAG Swarms)
- SwarmCheckpointStore & checkpoint_store (Session Resume Engine)
- AgentMessageBus & message_bus (Typed Pub/Sub Event Broker)
- SemanticMemoryCache & semantic_memory (Episodic Vector Recall)
- AgentWorkerPool & worker_pool (Sandboxed Isolation)
- PluginManifestEngine & plugin_engine (Micro-Kernel Plugin System)
- EphemeralContainerRunner & container_runner (Container Sandbox Isolation)
- SkillCatalog & UniversalMCPHub
"""

import importlib
from typing import Any

__all__ = [
    "TreeOfThoughtsOrchestrator",
    "tot_orchestrator",
    "ToTResult",
    "ThoughtNode",
    "CloudInfraOrchestrator",
    "cloud_infra_orchestrator",
    "CloudInfraPlan",
    "MultiRepoOrchestrator",
    "multirepo_orchestrator",
    "MultiRepoSyncPlan",
    "RepoTransform",
    "SiliconCircuitOrchestrator",
    "silicon_circuit_orchestrator",
    "SiliconCircuitDesign",
    "DebateConsensusOrchestrator",
    "debate_orchestrator",
    "DebateVerdict",
    "DebateRound",
    "TeamOrchestrator",
    "TeamResult",
    "SwarmPipelineEngine",
    "swarm_engine",
    "AutonomousSwarmRouter",
    "SwarmExecutionResult",
    "SwarmPipelineStage",
    "SwarmCheckpointStore",
    "checkpoint_store",
    "SwarmCheckpoint",
    "AgentWorkerPool",
    "worker_pool",
    "PluginManifestEngine",
    "plugin_engine",
    "EphemeralContainerRunner",
    "container_runner",
    "ContainerExecutionResult",
    "AgentMessageBus",
    "message_bus",
    "SemanticMemoryCache",
    "semantic_memory",
    "SkillCatalog",
    "skill_catalog",
    "UniversalMCPHub",
    "MCPHub",
    "mcp_hub",
    # 2026 Modular Domain Subsystems
    "loop",
    "harness",
    "rag",
    "graph",
    "cognitive",
    "verification",
    "telemetry",
    "swarm",
    "platform",
    "memory",
    "workflow",
    # Agent Personal Computer & Blackbox Workstation
    "AgentPersonalComputer",
    "AgentPC",
    "AgentSandbox",
    "AgentBlackbox",
    "WorkspaceFS",
    "PCCheckpoint",
    "get_agent_pc",
    "list_active_agent_pcs",
    # Frontier Alignment, PRM & Self-Correction
    "alignment",
    "RLHVRVerifier",
    "RLAIFAuditor",
    "RewardSignal",
    "RLCDGenerator",
    "RLCDPair",
    "RLHFStore",
    "HumanFeedback",
    "DPOBatchExporter",
    "ProcessRewardModel",
    "PRMMCTSEngine",
    "PRMMCTSResult",
    "CodeStep",
    "VerifiedSelfCorrectionEngine",
    "CorrectionResult",
    # Cross-File Interface Propagation & Sandbox Mock Virtualization
    "MultiFileInterfacePropagator",
    "CrossFileCallSite",
    "SignatureDelta",
    "PropagationResult",
    "SandboxMockSynthesizer",
    "VIRTUAL_MOCK_PRELUDE",
    "MultiFilePRM",
    "MultiFilePRMScore",
]

_MOD_MAP = {
    "AgentPersonalComputer": "agent_pc",
    "AgentPC": "agent_pc",
    "AgentSandbox": "agent_pc",
    "AgentBlackbox": "agent_pc",
    "WorkspaceFS": "agent_pc",
    "PCCheckpoint": "agent_pc",
    "get_agent_pc": "agent_pc",
    "list_active_agent_pcs": "agent_pc",

    "TreeOfThoughtsOrchestrator": "tot_orchestrator",
    "tot_orchestrator": "tot_orchestrator",
    "ToTResult": "tot_orchestrator",
    "ThoughtNode": "tot_orchestrator",
    "CloudInfraOrchestrator": "cloud_infra_orchestrator",
    "cloud_infra_orchestrator": "cloud_infra_orchestrator",
    "CloudInfraPlan": "cloud_infra_orchestrator",
    "MultiRepoOrchestrator": "multirepo_orchestrator",
    "multirepo_orchestrator": "multirepo_orchestrator",
    "MultiRepoSyncPlan": "multirepo_orchestrator",
    "RepoTransform": "multirepo_orchestrator",
    "SiliconCircuitOrchestrator": "silicon_circuit_orchestrator",
    "silicon_circuit_orchestrator": "silicon_circuit_orchestrator",
    "SiliconCircuitDesign": "silicon_circuit_orchestrator",
    "DebateConsensusOrchestrator": "debate_consensus_orchestrator",
    "debate_orchestrator": "debate_consensus_orchestrator",
    "DebateVerdict": "debate_consensus_orchestrator",
    "DebateRound": "debate_consensus_orchestrator",
    "TeamOrchestrator": "team_orchestrator",
    "TeamResult": "team_orchestrator",
    "SwarmPipelineEngine": "swarm_pipeline_engine",
    "swarm_engine": "swarm_pipeline_engine",
    "AutonomousSwarmRouter": "swarm_pipeline_engine",
    "SwarmExecutionResult": "swarm_pipeline_engine",
    "SwarmPipelineStage": "swarm_pipeline_engine",
    "SwarmCheckpointStore": "swarm_checkpoint_store",
    "checkpoint_store": "swarm_checkpoint_store",
    "SwarmCheckpoint": "swarm_checkpoint_store",
    "AgentWorkerPool": "agent_worker_pool",
    "worker_pool": "agent_worker_pool",
    "PluginManifestEngine": "plugin_manifest",
    "plugin_engine": "plugin_manifest",
    "EphemeralContainerRunner": "ephemeral_container_runner",
    "container_runner": "ephemeral_container_runner",
    "ContainerExecutionResult": "ephemeral_container_runner",
    "AgentMessageBus": "agent_message_bus",
    "message_bus": "agent_message_bus",
    "SemanticMemoryCache": "semantic_memory_cache",
    "semantic_memory": "semantic_memory_cache",
    "SkillCatalog": "skill_catalog",
    "skill_catalog": "skill_catalog",
    "UniversalMCPHub": "mcp_hub",
    "mcp_hub": "mcp_hub",
    "TokenLedger": "token_ledger",
    "token_ledger": "token_ledger",
    "StatsTracker": "stats_tracker",
    "NanosecondLatencyHistogram": "latency_histogram",
    "HardwareProfiler": "hardware_profiler",
    "PerformanceProfiler": "performance_profiler",
    "performance_profiler": "performance_profiler",
    "SalehaSwarmTopology": "saleha_swarm_topology",
    "P2PMeshNode": "p2p_mesh",
    "SwarmClusterNode": "swarm_cluster_node",
    "swarm_cluster": "swarm_cluster_node",
    "BatchedFuzzingEngine": "p2p_swarm",
    "batched_fuzzing_engine": "p2p_swarm",
    "SwarmSelfPlayArena": "swarm_self_play_arena",
    "swarm_self_play_arena": "swarm_self_play_arena",
    "BM25Index": "bm25",
    "bm25_index": "bm25",
    "FastSearchEngine": "fast_search",
    "fast_search_engine": "fast_search",
    "GraphRAGEngine": "graph_rag",
    "graph_rag": "graph_rag",
    "OllamaEmbedder": "embedding_backends",
    "SemanticCache": "semantic_cache",
    "semantic_cache": "semantic_cache",
    "MemoryStore": "memory_store",
    "memory_store": "memory_store",
    "MemoryJournal": "memory_journal",
    "memory_journal": "memory_journal",
    "ProjectMemory": "project_memory",
    "get_project_memory": "project_memory",
    "TriTierMemoryEngine": "tri_tier_memory",
    "tri_tier_memory": "tri_tier_memory",
    # Alignment, PRM & Self-Correction
    "RLHVRVerifier": "verifiable_rewards",
    "RLAIFAuditor": "verifiable_rewards",
    "RewardSignal": "verifiable_rewards",
    "RLCDGenerator": "contrastive_rlcd",
    "RLCDPair": "contrastive_rlcd",
    "RLHFStore": "preference_store",
    "HumanFeedback": "preference_store",
    "DPOBatchExporter": "preference_store",
    "ProcessRewardModel": "prm_mcts_engine",
    "PRMMCTSEngine": "prm_mcts_engine",
    "PRMMCTSResult": "prm_mcts_engine",
    "CodeStep": "prm_mcts_engine",
    "VerifiedSelfCorrectionEngine": "self_correction",
    "CorrectionResult": "self_correction",
    "MultiFileInterfacePropagator": "multi_file_interface_propagator",
    "CrossFileCallSite": "multi_file_interface_propagator",
    "SignatureDelta": "multi_file_interface_propagator",
    "PropagationResult": "multi_file_interface_propagator",
    "SandboxMockSynthesizer": "sandbox_mock_synthesizer",
    "VIRTUAL_MOCK_PRELUDE": "sandbox_mock_synthesizer",
    "MultiFilePRM": "multi_file_prm",
    "MultiFilePRMScore": "multi_file_prm",
}


_SUBPACKAGES = {
    "alignment", "cognitive", "daemons", "db", "devops", "docs", "editing", "git", "github",
    "governance", "graph", "harness", "loop", "memory", "platform", "plugins", "polyglot",
    "project", "rag", "research", "review", "sandbox", "security", "skills", "swarm",
    "telemetry", "training", "ui", "verification", "vision", "voice", "workflow",
}

# Every flat module name that moved into one of the category subpackages
# above (see saleha/STRUCTURE.md); their dotted path now needs the category
# prefix. Covers both "from saleha.core import <module_name>" (the module
# itself) and _MOD_MAP entries whose target moved. Modules not listed here
# are still flat directly under saleha/core/.
_MOD_TO_SUBPACKAGE = {
    "causal_world_model": "cognitive", "neuro_symbolic_engine": "cognitive",
    "padic_ultrametric": "cognitive", "persona_debate": "cognitive", "soul_engine": "cognitive",
    "codebase_indexer": "graph", "dependency_graph": "graph", "graph_memory": "graph",
    "hypergraph_indexer": "graph", "multi_repo_graph": "graph", "system1_scout": "graph",
    "approval_gate": "harness", "benchmark_harness": "harness", "code_executor": "harness",
    "sandbox_runner": "harness", "swebench_runner": "harness", "test_runner": "harness",
    "agentic_loop": "loop", "deliberation_engine": "loop", "recursive_solver": "loop",
    "tot_orchestrator": "loop",
    "git_native": "platform", "lsp_engine": "platform", "mcp_hub": "platform",
    "model_provider": "platform", "self_healer": "platform", "smart_router": "platform",
    "repo_context_packer": "rag", "semantic_search": "rag", "tree_context_ranker": "rag",
    "vector_store": "rag", "bm25": "rag", "fast_search": "rag", "graph_rag": "rag",
    "embedding_backends": "rag", "semantic_cache": "rag",
    "agent_message_bus": "swarm", "agent_worker_pool": "swarm", "swarm_checkpoint_store": "swarm",
    "swarm_consensus": "swarm", "swarm_pipeline_engine": "swarm", "team_orchestrator": "swarm",
    "p2p_mesh": "swarm", "p2p_swarm": "swarm", "saleha_swarm_topology": "swarm",
    "swarm_cluster_node": "swarm", "swarm_self_play_arena": "swarm",
    "audit_log": "telemetry", "metrics": "telemetry", "session_tracer": "telemetry",
    "token_analytics": "telemetry", "latency_histogram": "telemetry",
    "stats_tracker": "telemetry", "token_ledger": "telemetry",
    "hardware_profiler": "telemetry", "performance_profiler": "telemetry",
    "apex_97_validator": "verification", "formal_smt_verifier": "verification",
    "quality_guard": "verification", "safety_guard": "verification",
    "security_scanner": "verification", "ttc_solver": "verification",
    "memory_store": "memory", "memory_journal": "memory", "project_memory": "memory",
    "semantic_memory_cache": "memory", "tri_tier_memory": "memory",
    "verifiable_rewards": "alignment", "contrastive_rlcd": "alignment", "preference_store": "alignment",
    "multi_file_prm": "alignment",
    # Moved 2026-09-29: every remaining flat module except four another agent
    # was editing (proof_receipt, silicon_scanner, tourist_solver, work_ledger).
    "prm_mcts_engine": "alignment",
    "active_inference": "cognitive", "causal_trace": "cognitive", "cognitive_engine": "cognitive",
    "saleha_watchdog": "daemons", "sidecar_daemon": "daemons", "task_scheduler": "daemons",
    "db_optimizer": "db",
    "chaos_engine": "devops", "cloud_deployer": "devops", "cloud_infra_orchestrator": "devops",
    "deployer": "devops", "env_sync": "devops", "infra_generator": "devops",
    "load_tester": "devops", "mock_server": "devops", "sre_responder": "devops",
    "autodoc_generator": "docs", "changelog_generator": "docs", "doc_researcher": "docs",
    "docs_generator": "docs",
    "code_migrator": "editing", "diff_engine": "editing", "multi_file_auto_repair": "editing",
    "multi_file_editor": "editing", "multi_file_interface_propagator": "editing",
    "multi_file_refactorer": "editing",
    "conflict_resolver": "git", "git_hooks": "git", "time_machine": "git",
    "github_integrator": "github", "issue_resolver": "github", "pr_generator": "github",
    "pr_reviewer": "github",
    "change_impact": "graph", "incremental_ast_cache": "graph", "repo_graph": "graph",
    "benchmark_reporter": "harness", "evaluator": "harness", "hard_task_bench": "harness",
    "real_task_bench": "harness", "swe_bench_exporter": "harness", "swe_bench_harness": "harness",
    "swe_bench_runner": "harness", "swe_leaderboard": "harness", "test_arbiter": "harness",
    "action_menu": "loop", "debugger_repl": "loop", "local_supremacy": "loop",
    "mcts_search_engine": "loop", "parallel_solver": "loop", "self_correction": "loop",
    "self_evolving_loop": "loop", "self_healing": "loop", "self_improve": "loop",
    "structured_reasoner": "loop",
    "session_store": "memory", "task_history": "memory",
    "agent_profile_loader": "platform", "collab": "platform", "context_budget": "platform",
    "fast_inference": "platform", "hybrid_gateway": "platform",
    "inference_router_bridge": "platform", "intent_kernel": "platform",
    "local_inference_engine": "platform", "lsp_server": "platform", "mcp_engine": "platform",
    "mcp_server": "platform", "model_manager": "platform", "ollama_endpoint": "platform",
    "path_utils": "platform", "sandboxed_mcp_client": "platform",
    "speculative_accelerator": "platform", "user_store": "platform", "websocket_bridge": "platform",
    "plugin_hub": "plugins", "plugin_loader": "plugins", "plugin_manifest": "plugins",
    "native_compiler": "polyglot", "polyglot_ast_engine": "polyglot",
    "polyglot_executor": "polyglot", "polyglot_indexer": "polyglot",
    "htmx_generator": "project", "multirepo_orchestrator": "project", "project_builder": "project",
    "project_initializer": "project", "project_scaffolder": "project",
    "repo_orchestrator": "project", "workspace_coordinator": "project",
    "doom_vault": "research", "doom_workspace_engine": "research", "godel_utility": "research",
    "hyperbolic_engine": "research", "iot_domotics": "research", "math_logic": "research",
    "mech_interp": "research", "mukti_chain_bridge": "research", "mukti_economy": "research",
    "neural_designer": "research", "nexus_mobile_bridge": "research",
    "omni_arena_engine": "research", "quantum_compiler": "research", "sheaf_consensus": "research",
    "silicon_circuit_orchestrator": "research", "spatial_coder": "research",
    "unimax_bridge": "research", "webgpu_accelerator": "research",
    "ai_reviewer": "review", "ensemble_reviewer": "review", "review_reporter": "review",
    "tech_debt_analyzer": "review",
    "agent_pc": "sandbox", "docker_sandbox": "sandbox", "ephemeral_container_runner": "sandbox",
    "execution_policy": "sandbox", "gamma_critic_sandbox": "sandbox", "hardened_sandbox": "sandbox",
    "prewarmed_sandbox_pool": "sandbox", "saleha_wasm_runtime": "sandbox",
    "sandbox_mock_synthesizer": "sandbox", "wasm_runner": "sandbox",
    "windows_job_sandbox": "sandbox",
    "agent_permissions": "security", "api_fuzzer": "security", "constitutional_guard": "security",
    "merkle_provenance": "security", "pqc_guard": "security", "red_team_engine": "security",
    "safety_patterns": "security", "sentinel_rs": "security", "spics_fuzz_engine": "security",
    "threat_modeler": "security", "untrusted_content": "security", "vault": "security",
    "skill_base": "skills", "skill_catalog": "skills", "skill_registry": "skills",
    "skill_synthesizer": "skills", "tool_calling": "skills", "tool_forge": "skills",
    "agent_contracts": "swarm", "agent_council": "swarm", "architecture_debater": "swarm",
    "context_board": "swarm", "debate_consensus_orchestrator": "swarm",
    "distributed_server": "swarm", "emergence_detector": "swarm", "octopus_coordinator": "swarm",
    "quadratic_voting": "swarm",
    "dataset_synthesizer": "training", "dpo_dataset_engine": "training",
    "dynamic_lora_router": "training", "frontier_trainer": "training",
    "grpo_reasoning_trainer": "training", "lora_tuner": "training",
    "model_distillation_pipeline": "training", "prompt_evolution": "training",
    "prompt_optimizer": "training", "training_collector": "training",
    "graph_visualizer": "ui", "inline_suggester": "ui", "notebook_engine": "ui",
    "realtime_watcher": "ui", "repo_watcher": "ui", "streaming_ui": "ui", "web_dashboard": "ui",
    "formal_verifier": "verification", "task_evidence": "verification",
    "browser_agent": "vision", "browser_runner": "vision", "browser_tester": "vision",
    "saleha_multimodal": "vision", "vision_backend": "vision", "vision_coder": "vision",
    "vision_liveness": "vision", "visual_diff": "vision",
    "full_duplex_voice": "voice", "speech": "voice", "voice_assistant": "voice",
    "voice_engine": "voice", "voice_live": "voice",
    "dag_engine": "workflow",
}


def __getattr__(name: str) -> Any:
    if name in _SUBPACKAGES:
        return importlib.import_module(f"saleha.core.{name}")
    if name == "MCPHub":
        mod = importlib.import_module("saleha.core.platform.mcp_hub")
        return mod.UniversalMCPHub
    if name in _MOD_TO_SUBPACKAGE:
        # "from saleha.core import <module_name>" -- the module itself moved.
        return importlib.import_module(f"saleha.core.{_MOD_TO_SUBPACKAGE[name]}.{name}")
    if name in _MOD_MAP:
        target = _MOD_MAP[name]
        subpackage = _MOD_TO_SUBPACKAGE.get(target)
        dotted = f"saleha.core.{subpackage}.{target}" if subpackage else f"saleha.core.{target}"
        mod = importlib.import_module(dotted)
        return getattr(mod, name)
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")

