"""
Saleha Core: Auto-Documentation & Mermaid Diagram Generator

Parses Abstract Syntax Trees (AST) to automatically generate Markdown API reference manuals,
Mermaid architecture/sequence diagrams, and OpenAPI schemas from codebase docstrings and type hints.
"""

import ast
import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from saleha.core.path_utils import safe_relpath


@dataclass
class AutoDocResult:
    total_modules: int
    total_classes: int
    total_functions: int
    markdown_docs: str
    mermaid_diagram: str


class AutoDocGenerator:
    """Generates Markdown API docs and Mermaid architecture diagrams from AST."""

    def generate_docs_for_directory(self, root_dir: str = ".") -> AutoDocResult:
        """Scans directory and compiles comprehensive API reference & diagrams."""
        modules_count = 0
        classes_count = 0
        functions_count = 0

        doc_sections = ["# 📚 Codebase API Documentation\n*Auto-generated by Saleha AI*\n"]
        mermaid_nodes = ["flowchart TD"]

        for root, _, files in os.walk(root_dir):
            rel_parts = safe_relpath(root, root_dir).split(os.sep)
            if any((p.startswith(".") and p not in (".", "..")) or p in ("node_modules", "venv", "__pycache__", "build", "dist", ".git") for p in rel_parts):
                continue

            for f in files:
                if f.endswith(".py"):
                    full_path = os.path.join(root, f)
                    rel_path = safe_relpath(full_path, root_dir).replace("\\", "/")
                    try:
                        with open(full_path, "r", encoding="utf-8", errors="ignore") as pyf:
                            code = pyf.read()
                        tree = ast.parse(code, filename=rel_path)
                        modules_count += 1

                        doc_sections.append(f"## Module `{rel_path}`\n")
                        mod_doc = ast.get_docstring(tree)
                        if mod_doc:
                            doc_sections.append(f"*{mod_doc.strip()}*\n")

                        safe_mod_id = rel_path.replace("/", "_").replace(".", "_")

                        for node in ast.iter_child_nodes(tree):
                            if isinstance(node, ast.ClassDef):
                                classes_count += 1
                                c_doc = ast.get_docstring(node) or "No description."
                                doc_sections.append(f"### `class {node.name}`\n{c_doc.strip()}\n")
                                mermaid_nodes.append(f"    {safe_mod_id} --> {node.name}[Class: {node.name}]")
                            elif isinstance(node, ast.FunctionDef):
                                functions_count += 1
                                f_doc = ast.get_docstring(node) or "No description."
                                doc_sections.append(f"#### `def {node.name}(...)`\n{f_doc.strip()}\n")

                    except Exception:
                        pass

        full_md = "\n".join(doc_sections)
        full_mermaid = "\n".join(mermaid_nodes)

        return AutoDocResult(
            total_modules=modules_count,
            total_classes=classes_count,
            total_functions=functions_count,
            markdown_docs=full_md,
            mermaid_diagram=full_mermaid
        )


# Global instance
autodoc_generator = AutoDocGenerator()

