"""
Saleha Core: Cloud Infrastructure scaffold generator.

Emits a fixed starting-point set of IaC files -- Terraform, Kubernetes
manifests, Helm values, an IAM policy and a CI/CD workflow -- so a project has
something to edit instead of a blank directory.

## Read this before trusting the output

**These are templates. They are not designed from your request.** Nothing here
reads the goal, calls a model, or reasons about infrastructure. Measured, with
two unrelated goals:

    "Design a multi-region Postgres cluster"  vs  "Write a haiku about frogs"

    kubernetes_manifests : byte-identical
    helm_values          : byte-identical
    iam_policy_json      : byte-identical
    ci_cd_workflow       : byte-identical
    terraform_code       : differs on 3 lines -- all of them the goal string
                           echoed into a comment, the S3 state key and a tag

Specific things the caller must know:

- **The provider argument only changes a name.** Ask for `gcp` or `azure` and
  you still get AWS: an S3 backend, `us-east-1`, `terraform-aws-modules/vpc/aws`
  and AWS subnet CIDRs, with `hashicorp/gcp` written in the required_providers
  block -- which is not even a real provider address (it is `hashicorp/google`).
  That configuration cannot `terraform init`.
- **The cost is a constant**, not an estimate: 142.50 with HA, 48.00 without,
  for any architecture in any region.
- **The security score is the literal 96**, from no analysis of anything.
- **The IAM policy is not least-privilege.** It grants its actions on
  `"Resource": "*"`.

Treat the output as a skeleton to rewrite, never as a reviewed design. The
dataclass carries `is_template=True` and `caveats` so callers cannot present it
as generated infrastructure by accident.
"""

from __future__ import annotations

import os
import json
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from pathlib import Path


# Every caveat below is a measured fact about this generator, not a hedge.
# They travel with the result so a caller cannot render it as a real design.
TEMPLATE_CAVEATS = (
    "These files are fixed templates; nothing was designed from the goal.",
    "The provider option only substitutes a name -- the Terraform is AWS "
    "regardless, and will not `terraform init` for gcp/azure.",
    "The monthly cost is a constant, not an estimate.",
    "The IAM policy grants its actions on Resource '*'; it is not "
    "least-privilege.",
    "No security analysis was performed.",
)


@dataclass
class CloudInfraPlan:
    goal: str
    cloud_provider: str  # "aws", "gcp", "azure", "cloudflare"
    terraform_code: str
    kubernetes_manifests: str
    helm_values: str
    iam_policy_json: str
    ci_cd_workflow: str
    # Constants, not measurements. `None` is the honest value for a figure
    # nothing computed; the previous code returned 142.50 and 96 for every
    # architecture in every region, presented as an estimate and a score.
    finops_estimated_monthly_cost: Optional[float] = None
    security_score: Optional[int] = None
    # Fixed template output, not generated from the request.
    is_template: bool = True
    caveats: List[str] = field(default_factory=lambda: list(TEMPLATE_CAVEATS))
    # Set when the requested provider is not the one the template emits.
    provider_mismatch: str = ""


class CloudInfraOrchestrator:
    """Specialized Orchestrator for Enterprise Cloud Infrastructure & DevOps."""

    def __init__(self):
        pass

    def plan_and_generate_infra(
        self,
        goal: str,
        cloud_provider: str = "aws",
        high_availability: bool = True
    ) -> CloudInfraPlan:
        """Synthesizes comprehensive cloud infrastructure blueprints."""
        provider = cloud_provider.lower()

        # 1. Synthesize Terraform Architecture
        tf_template = f"""# ==============================================================================
# Terraform Infrastructure for: {goal}
# Provider: {provider.upper()} | High Availability: {high_availability}
# Generated by Saleha CloudInfraOrchestrator v2.6.0
# ==============================================================================

terraform {{
  required_version = ">= 1.6.0"
  required_providers {{
    {provider} = {{
      source  = "hashicorp/{provider}"
      version = "~> 5.0"
    }}
  }}
  backend "s3" {{
    bucket         = "saleha-terraform-state-prod"
    key            = "infra/{goal.lower().replace(' ', '_')}/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "saleha-tf-locks"
    encrypt        = true
  }}
}}

provider "{provider}" {{
  region = "us-east-1"
  default_tags {{
    tags = {{
      Environment = "production"
      ManagedBy   = "Saleha-CloudOrchestrator"
      Project     = "{goal[:30]}"
    }}
  }}
}}

module "vpc" {{
  source  = "terraform-aws-modules/vpc/aws"
  version = "~> 5.0"

  name = "saleha-prod-vpc"
  cidr = "10.0.0.0/16"

  azs             = ["us-east-1a", "us-east-1b", "us-east-1c"]
  private_subnets = ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"]
  public_subnets  = ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"]

  enable_nat_gateway   = true
  single_nat_gateway   = false
  enable_dns_hostnames = true
}}
"""

        # 2. Synthesize Kubernetes Manifests
        k8s_manifests = f"""# Kubernetes Deployment & Service Manifests
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleha-workload
  labels:
    app.kubernetes.io/name: saleha-workload
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saleha-workload
  template:
    metadata:
      labels:
        app: saleha-workload
    spec:
      containers:
      - name: app
        image: ghcr.io/mdaftab76678-1945/saleha:latest
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: saleha-workload-svc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: saleha-workload
"""

        # 3. FinOps Cost Estimation
        est_cost = 142.50 if high_availability else 48.00

        # 4. IAM Least Privilege JSON
        iam_json = json.dumps({
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "SalehaLeastPrivilegeAccess",
                    "Effect": "Allow",
                    "Action": [
                        "s3:GetObject",
                        "s3:PutObject",
                        "ec2:DescribeInstances",
                        "rds:DescribeDBInstances"
                    ],
                    "Resource": "*"
                }
            ]
        }, indent=2)

        # 5. CI/CD GitHub Actions Workflow
        ci_cd = """name: Cloud Infrastructure CI/CD
on:
  push:
    branches: [main]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
"""

        # The Terraform body is AWS whatever provider was asked for. Say so in
        # the result rather than letting the caller discover it at `terraform
        # init`, and warn inside the file itself so it survives being written
        # to disk and read later out of context.
        mismatch = ""
        if provider != "aws":
            mismatch = (
                f"Requested provider '{provider}', but the Terraform emitted "
                f"is AWS (S3 backend, us-east-1, terraform-aws-modules/vpc/aws). "
                f"It will not initialise as {provider}."
            )
            tf_template = (
                f"# WARNING: requested provider was '{provider}', but this is "
                f"an AWS template. It will not `terraform init` unmodified.\n"
                + tf_template
            )

        caveats = list(TEMPLATE_CAVEATS)
        if mismatch:
            caveats.insert(0, mismatch)

        return CloudInfraPlan(
            goal=goal,
            cloud_provider=provider,
            terraform_code=tf_template,
            kubernetes_manifests=k8s_manifests,
            helm_values="replicaCount: 3\nautoscaling:\n  enabled: true\n  minReplicas: 3\n  maxReplicas: 10\n",
            finops_estimated_monthly_cost=est_cost,
            iam_policy_json=iam_json,
            ci_cd_workflow=ci_cd,
            security_score=None,
            is_template=True,
            caveats=caveats,
            provider_mismatch=mismatch,
        )


# Global Singleton Cloud Infra Orchestrator
cloud_infra_orchestrator = CloudInfraOrchestrator()
