"""
Saleha Core: Autonomous Database Migration & Schema Optimizer

Analyzes SQL schemas and ORM queries to generate reversible SQL migrations, detect missing
foreign key indexes, and flag N+1 query performance bottlenecks.
"""

import re
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any


@dataclass
class SchemaAnalysis:
    tables_found: List[str]
    missing_indexes: List[str]
    n_plus_one_risks: List[str]
    migration_sql_up: str
    migration_sql_down: str


class DBOptimizer:
    """Analyzes database schemas and generates optimized SQL migrations."""

    def analyze_schema(self, ddl_or_code: str) -> SchemaAnalysis:
        """Parses DDL or ORM definitions to detect indexing gaps and generate migrations."""
        tables = re.findall(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([a-zA-Z0-9_]+)", ddl_or_code, re.IGNORECASE)
        fk_columns = re.findall(r"([a-zA-Z0-9_]+_id)\s+[a-zA-Z0-9_]+", ddl_or_code, re.IGNORECASE)
        fk_cols = list(dict.fromkeys(fk_columns))

        missing_indexes = []
        up_migrations = ["-- ====================================", "-- MIGRATION UP (Auto-Generated by Saleha)", "-- ===================================="]
        down_migrations = ["-- ====================================", "-- MIGRATION DOWN (Rollback)", "-- ===================================="]

        for col in fk_cols:
            idx_name = f"idx_{col}"
            if idx_name not in ddl_or_code:
                missing_indexes.append(f"Foreign key column `{col}` lacks an explicit B-tree index.")
                up_migrations.append(f"CREATE INDEX IF NOT EXISTS {idx_name} ON target_table ({col});")
                down_migrations.append(f"DROP INDEX IF EXISTS {idx_name};")

        # Detect N+1 patterns
        n_plus_one = []
        if re.search(r"for\s+\w+\s+in\s+.*:\s+.*\.query|\.select", ddl_or_code, re.DOTALL):
            n_plus_one.append("Potential N+1 query loop detected: Query execution found inside iteration loop. Consider using `joinedload()` or `selectinload()`.")

        return SchemaAnalysis(
            tables_found=tables,
            missing_indexes=missing_indexes,
            n_plus_one_risks=n_plus_one,
            migration_sql_up="\n".join(up_migrations),
            migration_sql_down="\n".join(down_migrations)
        )


# Global instance
db_optimizer = DBOptimizer()

