"""
Saleha Core: GRPO (Group Relative Policy Optimization) Reasoning Scorer

Runs a real group-rollout comparison for a coding prompt:

1. G real candidates are generated by CoderAgent (real model calls, one
   generation per rollout -- no template code, no canned <think> text).
2. Each candidate is scored by the real AST security scanner and the real
   neuro-symbolic invariant scorer (the same scorers swarm_self_play_arena.py
   uses), not a synthetic per-index formula.
3. Group-relative advantage (A_i = (R_i - mean) / std) is computed from
   those real scores -- this part of GRPO is genuine arithmetic either way,
   so it stays.

What this module does NOT do, and used to fake:
- No policy weight update. Computing an advantage signal is not the same as
  applying a policy-gradient step to model weights; that requires a training
  loop this project does not have wired up (same gap frontier_trainer.py
  reports for its RLIF phase). `policy_loss`/`kl_divergence` are no longer
  returned -- there is no policy being optimized.
- No <think> reasoning trace synthesis. The earlier version handed back a
  hardcoded, prompt-independent paragraph as if it were a model's own
  reasoning. Real chain-of-thought would have to come from the model's own
  output; nothing here manufactures it.
- No red-team/adversarial neutralization count and no "deployed model" name.
  Both were constants with no red-team run and no `ollama create` call
  behind them.

Renamed the summary field `deployed_model_name` did not survive either --
nothing here deploys anything.
"""

from __future__ import annotations

import math
import os
import time
from dataclasses import dataclass, field
from typing import List, Optional

from saleha.agents.coder import CoderAgent
from saleha.core.neuro_symbolic_engine import neuro_symbolic_engine
from saleha.core.security_scanner import ASTSecurityScanner


@dataclass
class GRPORollout:
    rollout_id: str
    code: str
    model_used: str
    generation_succeeded: bool
    ast_valid: bool
    security_findings_unresolved: int  # HIGH severity findings
    composite_score: float  # from neuro_symbolic_engine, 0.0-1.0
    total_reward: float = 0.0
    normalized_advantage: float = 0.0


@dataclass
class GRPOTrainingStepResult:
    step: int
    prompt: str
    group_size: int
    rollouts: List[GRPORollout]
    group_mean_reward: float
    group_std_reward: float
    winner_rollout: GRPORollout


@dataclass
class GRPOTrainingSummary:
    total_steps: int
    total_rollouts: int
    initial_mean_reward: float
    final_mean_reward: float
    steps: List[GRPOTrainingStepResult] = field(default_factory=list)
    training_duration_sec: float = 0.0
    note: str = (
        "This measures group-relative reward signal only. No policy weight "
        "update is applied -- that would need a training loop this project "
        "does not have wired up (same gap as frontier_trainer.py's RLIF phase)."
    )


class GRPOReasoningTrainer:
    """Group Relative Policy Optimization (GRPO) reward scorer.

    Real candidates, real scoring, real group-relative-advantage arithmetic.
    Does not train anything -- see module docstring for what was removed
    and why.
    """

    def __init__(self, group_size: int = 4, work_dir: Optional[str] = None):
        self.group_size = max(2, group_size)
        self.work_dir = work_dir or os.path.expanduser("~/.saleha/grpo_scoring")
        os.makedirs(self.work_dir, exist_ok=True)
        self._coder = CoderAgent(model="auto")
        self._scanner = ASTSecurityScanner()

    def _sample_group_rollouts(self, prompt: str) -> List[GRPORollout]:
        """Generates G real candidate solutions and scores each for real."""
        rollouts: List[GRPORollout] = []
        for i in range(self.group_size):
            code_result = self._coder.generate_code(prompt, attempt=i + 1)
            ok = code_result.success and bool(code_result.code.strip())

            if not ok:
                rollouts.append(
                    GRPORollout(
                        rollout_id=f"rollout_{i + 1}",
                        code=code_result.code,
                        model_used=code_result.model_used,
                        generation_succeeded=False,
                        ast_valid=False,
                        security_findings_unresolved=0,
                        composite_score=0.0,
                        total_reward=0.0,
                    )
                )
                continue

            vulns = self._scanner.scan_code(code_result.code, filename="candidate.py")
            unresolved = sum(1 for v in vulns if v.severity == "HIGH")
            inv = neuro_symbolic_engine.score_code(code_result.code)
            security_factor = 1.0 if unresolved == 0 else max(0.0, 1.0 - 0.25 * unresolved)

            # Reward = invariant quality weighted with a security penalty.
            total_r = round((0.7 * inv.composite_score) + (0.3 * security_factor), 4)

            rollouts.append(
                GRPORollout(
                    rollout_id=f"rollout_{i + 1}",
                    code=code_result.code,
                    model_used=code_result.model_used,
                    generation_succeeded=True,
                    ast_valid=inv.ast_valid,
                    security_findings_unresolved=unresolved,
                    composite_score=inv.composite_score,
                    total_reward=total_r,
                )
            )

        rewards = [r.total_reward for r in rollouts]
        mean_r = sum(rewards) / len(rewards)
        variance = sum((r - mean_r) ** 2 for r in rewards) / len(rewards)
        std_r = math.sqrt(max(1e-6, variance))
        for r in rollouts:
            r.normalized_advantage = round((r.total_reward - mean_r) / std_r, 4)

        return rollouts

    def train_step(self, step: int, prompt: str) -> GRPOTrainingStepResult:
        """Runs one real group rollout for a prompt and reports its reward spread."""
        rollouts = self._sample_group_rollouts(prompt)
        rollouts.sort(key=lambda r: r.total_reward, reverse=True)

        rewards = [r.total_reward for r in rollouts]
        mean_r = round(sum(rewards) / len(rewards), 4)
        std_r = round(math.sqrt(sum((r - mean_r) ** 2 for r in rewards) / len(rewards)), 4)

        return GRPOTrainingStepResult(
            step=step,
            prompt=prompt,
            group_size=self.group_size,
            rollouts=rollouts,
            group_mean_reward=mean_r,
            group_std_reward=std_r,
            winner_rollout=rollouts[0],
        )

    def run_full_grpo_training(self, target_steps: int = 3) -> GRPOTrainingSummary:
        """Runs real group-rollout scoring across a fixed set of prompts.

        Named run_*_training for backward compatibility with existing
        callers; it does not train a model -- see module docstring.
        """
        start_t = time.time()
        prompts = [
            "Implement a thread-safe LRU cache",
            "Write a function that validates balanced parentheses",
            "Implement binary search over a sorted list",
        ]

        steps_results: List[GRPOTrainingStepResult] = []
        for idx in range(min(target_steps, len(prompts))):
            res = self.train_step(step=idx + 1, prompt=prompts[idx])
            steps_results.append(res)

        duration = round(time.time() - start_t, 2)
        initial_mean = steps_results[0].group_mean_reward if steps_results else 0.0
        final_mean = steps_results[-1].group_mean_reward if steps_results else 0.0

        return GRPOTrainingSummary(
            total_steps=len(steps_results),
            total_rollouts=sum(s.group_size for s in steps_results),
            initial_mean_reward=initial_mean,
            final_mean_reward=final_mean,
            steps=steps_results,
            training_duration_sec=duration,
        )


grpo_reasoning_trainer = GRPOReasoningTrainer()
