"""
Saleha Core: Multi-Repo migration checklist generator.

Given a goal and a list of repository names, produces a suggested branch name,
a PR title, and a migration order per repository -- a checklist to work from
when a change has to land across several services.

## What this does NOT do

It does not read the repositories. It never has. Nothing here clones, opens,
parses or diffs a single file, and no model is called.

Measured, asking it to "Rename button colour to blue" across
`payments-api` and `web-frontend`:

    files_changed : ['payments-api/models.py', 'payments-api/router.py']
    do they exist : [False, False]
    diff_content  : "+    id: UUID"  /  "+    created_at: datetime"

The diff is a fixed illustration -- it adds a UUID and a timestamp regardless
of the goal. The file names are guessed from the repo name plus a hardcoded
suffix, chosen by whether the repo name contains "api", "contract", "backend",
"proto" or "schema".

The PR body used to end with three ticked checkboxes:

    - [x] Zero breaking change contract mismatch
    - [x] AST compatibility verified
    - [x] End-to-end integration tests passing

None of those checks exist anywhere in this module. That is the same
fabricated-green defect that `/autopr` had, multiplied across every repository
in the list. The checkboxes are now unticked and labelled as work for the
person doing the migration.

`is_atomic` is likewise a claim this module cannot make: nothing here can make
changes across independent repositories atomic. It reports the ordering only.
"""

from __future__ import annotations

import os
import json
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any


@dataclass
class RepoTransform:
    repo_name: str
    branch_name: str
    # Guessed from the repo name, not read from the repository. Renamed from
    # `files_changed`, which asserted something this module cannot know.
    likely_files: List[str]
    # A fixed illustrative snippet, identical for every goal. Renamed from
    # `diff_content` so no caller mistakes it for a real diff.
    example_diff: str
    pr_title: str
    pr_body: str


@dataclass
class MultiRepoSyncPlan:
    goal: str
    affected_repos: List[str]
    # Repos whose NAME suggests they publish a contract. Not an analysis of
    # what actually breaks -- renamed from `breaking_changes_identified`,
    # which claimed an inspection that never happened.
    likely_contract_repos: List[str]
    transforms: Dict[str, RepoTransform]
    migration_order: List[str] = field(default_factory=list)
    # Fixed template output; no repository was read.
    is_template: bool = True
    caveats: List[str] = field(default_factory=lambda: [
        "No repository was read: file names are guessed from the repo name and "
        "the example diff is the same for every goal.",
        "Ordering is a heuristic on repo names ('api', 'contract', 'backend', "
        "'proto', 'schema' go first), not a dependency graph.",
        "Nothing here can make changes across independent repositories atomic.",
        "No compatibility check, AST check or test run was performed.",
    ])


class MultiRepoOrchestrator:
    """Specialized Orchestrator for Multi-Repository & Monorepo Microservices."""

    def __init__(self):
        pass

    def plan_multirepo_sync(
        self,
        goal: str,
        repos: List[str],
        contract_updates: Optional[Dict[str, Any]] = None
    ) -> MultiRepoSyncPlan:
        """Plans cross-repository atomic refactorings and correlated PR chains."""
        transforms: Dict[str, RepoTransform] = {}
        breaking_changes: List[str] = []
        migration_order: List[str] = []

        # Identify dependency graph order (e.g. backend/contracts -> consumers/frontend)
        for repo in repos:
            is_contract_provider = any(k in repo.lower() for k in ["api", "contract", "backend", "proto", "schema"])
            branch = f"saleha/sync-{repo.lower().replace('/', '-')}"
            
            if is_contract_provider:
                # Named by heuristic, not by inspection: the repo name merely
                # looks like a contract publisher.
                breaking_changes.append(repo)
                migration_order.insert(0, repo)
                diff = f"--- a/{repo}/models.py\n+++ b/{repo}/models.py\n@@ -10,2 +10,4 @@\n+    id: UUID\n+    created_at: datetime\n"
                files = [f"{repo}/models.py", f"{repo}/router.py"]
            else:
                migration_order.append(repo)
                diff = f"--- a/{repo}/client.ts\n+++ b/{repo}/client.ts\n@@ -15,2 +15,4 @@\n+    createdAt: string;\n"
                files = [f"{repo}/client.ts", f"{repo}/api.ts"]

            pr_body = f"""## Multi-repo migration checklist: {goal}

### Summary
Suggested branches and ordering, generated by Saleha. **No repository was
read** -- the file list below is guessed from the repo name and the diff is a
fixed illustration, the same for every goal.

### Repositories in this migration
{chr(10).join(f"- `{r}`" for r in repos)}

### Before merging -- none of this has been checked
- [ ] Contract compatibility confirmed
- [ ] Consumers updated and compiling
- [ ] Integration tests run across the affected services
- [ ] Rollout order confirmed (this tool orders by repo name, not by a
      dependency graph)
"""

            transforms[repo] = RepoTransform(
                repo_name=repo,
                branch_name=branch,
                likely_files=files,
                example_diff=diff,
                pr_title=f"chore(sync): {goal} [{repo}]",
                pr_body=pr_body
            )

        return MultiRepoSyncPlan(
            goal=goal,
            affected_repos=repos,
            likely_contract_repos=breaking_changes,
            transforms=transforms,
            migration_order=migration_order,
        )


# Global Singleton Multi-Repo Orchestrator
multirepo_orchestrator = MultiRepoOrchestrator()
