"""
Saleha Core: Verilog scaffold generator.

Emits a fixed 32-bit ALU module, a matching testbench and an SDC file, named
after the request -- a starting point for an RTL project rather than an empty
file.

## It does not design anything from the specification

The same ALU comes back for every request. Measured, with two unrelated specs:

    "4-bit ripple carry adder"  vs  "UART receiver with parity check"

    verilog_rtl : differs on ONE line -- the `// Description:` comment
    testbench   : byte-identical

The UART request returns an ALU with add/sub/and/or/xor/shift opcodes. There is
no receiver, no baud logic, no start bit. Nothing here parses the spec, calls a
model, or reasons about hardware.

Three further claims that were in this module and are now removed:

- **`estimated_lut_count = 184` and `estimated_max_freq_mhz = 450.0` were
  literals.** No synthesis tool was ever invoked, so there was nothing to
  estimate from. They also contradicted the SDC file this same function emits,
  which constrains the clock to 2.50ns -- 400 MHz, not 450.
- **`is_synthesizable = True` was unconditional.** No Yosys, Verilator or
  iverilog run backs it. The text is valid Verilog-2001 by construction, but
  that is a property of the template, not a synthesis result.
- **"self-checking UVM testbenches"** -- the testbench is plain Verilog with
  one hardcoded vector (15 + 25 = 40). It is not UVM and does not import it.

What is real: the emitted Verilog is syntactically valid, the testbench
instantiates the module correctly, and the SDC is well-formed. As a scaffold
that is useful. As a design for your specification it is nothing.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any


@dataclass
class SiliconCircuitDesign:
    module_name: str
    spec_goal: str
    verilog_rtl: str
    testbench_sv: str
    timing_constraints_sdc: str
    # The SDC constrains the clock to 2.50ns. This is what the template asks
    # for, not a measured achievable frequency -- the previous field
    # (`estimated_max_freq_mhz = 450.0`) was a literal that contradicted the
    # SDC this same function writes.
    sdc_target_freq_mhz: float = 400.0
    # None: no synthesis tool ran, so there is no gate or LUT count. The
    # previous `estimated_lut_count = 184` was a literal.
    estimated_lut_count: Optional[int] = None
    # None: unknown. Was unconditionally True with no toolchain behind it.
    is_synthesizable: Optional[bool] = None
    is_template: bool = True
    caveats: List[str] = field(default_factory=lambda: [
        "The same fixed 32-bit ALU is emitted for every specification; only "
        "the module name and a description comment change.",
        "No synthesis or simulation tool was run (no Yosys, Verilator or "
        "iverilog), so there is no LUT count, timing result or "
        "synthesizability verdict.",
        "The testbench is plain Verilog with one hardcoded vector, not UVM.",
        "sdc_target_freq_mhz is what the SDC file asks for, not an achieved "
        "frequency.",
    ])


class SiliconCircuitOrchestrator:
    """Specialized Hardware & Silicon RTL Synthesis Orchestrator."""

    def __init__(self):
        pass

    def synthesize_hardware_circuit(
        self,
        spec_goal: str,
        module_name: Optional[str] = None
    ) -> SiliconCircuitDesign:
        """Generates synthesizable Verilog RTL, testbench, and SDC timing constraints."""
        clean_name = module_name or re.sub(r"[^a-zA-Z0-9_]", "_", spec_goal.lower().split()[0])
        if not clean_name.startswith("saleha_"):
            clean_name = f"saleha_{clean_name}"

        # 1. Synthesizable Verilog RTL
        rtl = f"""// =============================================================================
// Module: {clean_name}
// Description: {spec_goal}
// Generated by Saleha SiliconCircuitOrchestrator v2.6.0 (IEEE 1364-2005)
// =============================================================================

`timescale 1ns / 1ps

module {clean_name} #(
    parameter DATA_WIDTH = 32,
    parameter ADDR_WIDTH = 8
)(
    input  wire                   clk,
    input  wire                   rst_n,
    input  wire                   valid_in,
    input  wire [DATA_WIDTH-1:0]  data_in_a,
    input  wire [DATA_WIDTH-1:0]  data_in_b,
    input  wire [3:0]             op_code,
    output reg                    valid_out,
    output reg  [DATA_WIDTH-1:0]  data_out,
    output reg                    overflow_flag
);

    // Synchronous Pipelined Execution Stage
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            valid_out     <= 1'b0;
            data_out      <= {{DATA_WIDTH{{1'b0}}}};
            overflow_flag <= 1'b0;
        end else if (valid_in) begin
            valid_out <= 1'b1;
            case (op_code)
                4'b0000: data_out <= data_in_a + data_in_b; // ADD
                4'b0001: data_out <= data_in_a - data_in_b; // SUB
                4'b0010: data_out <= data_in_a & data_in_b; // AND
                4'b0011: data_out <= data_in_a | data_in_b; // OR
                4'b0100: data_out <= data_in_a ^ data_in_b; // XOR
                4'b0101: data_out <= data_in_a << data_in_b[4:0]; // SLL
                default: data_out <= {{DATA_WIDTH{{1'b0}}}};
            endcase
            // Detect arithmetic overflow
            overflow_flag <= (op_code == 4'b0000) && ((data_in_a + data_in_b) < data_in_a);
        end else begin
            valid_out <= 1'b0;
        end
    end

endmodule
"""

        # 2. Self-Checking Testbench
        testbench = f"""// =============================================================================
// Testbench: tb_{clean_name}
// Self-checking verification harness with randomized stimulus
// =============================================================================

`timescale 1ns / 1ps

module tb_{clean_name};

    parameter DATA_WIDTH = 32;

    reg                   clk;
    reg                   rst_n;
    reg                   valid_in;
    reg  [DATA_WIDTH-1:0] data_in_a;
    reg  [DATA_WIDTH-1:0] data_in_b;
    reg  [3:0]            op_code;
    wire                  valid_out;
    wire [DATA_WIDTH-1:0] data_out;
    wire                  overflow_flag;

    // Instantiate Unit Under Test (UUT)
    {clean_name} #(
        .DATA_WIDTH(DATA_WIDTH)
    ) uut (
        .clk(clk),
        .rst_n(rst_n),
        .valid_in(valid_in),
        .data_in_a(data_in_a),
        .data_in_b(data_in_b),
        .op_code(op_code),
        .valid_out(valid_out),
        .data_out(data_out),
        .overflow_flag(overflow_flag)
    );

    // 100MHz Clock Generator (10ns period)
    always #5 clk = ~clk;

    initial begin
        $dumpfile("{clean_name}_waves.vcd");
        $dumpvars(0, tb_{clean_name});

        clk = 0;
        rst_n = 0;
        valid_in = 0;
        data_in_a = 0;
        data_in_b = 0;
        op_code = 0;

        #20 rst_n = 1; // Release reset

        // Test Vector 1: ADD (15 + 25 = 40)
        #10;
        valid_in = 1;
        data_in_a = 32'd15;
        data_in_b = 32'd25;
        op_code = 4'b0000;

        #10;
        if (valid_out && data_out === 32'd40) begin
            $display("[PASS] Vector 1 ADD Success: %d", data_out);
        end else begin
            $display("[FAIL] Vector 1 ADD Error. Got: %d", data_out);
        end

        #20 $finish;
    end

endmodule
"""

        # 3. Synopsys Design Constraints (SDC)
        sdc = f"""# SDC Timing Constraints for {clean_name}
create_clock -name clk -period 2.50 [get_ports clk] # Target: 400 MHz
set_input_delay  -clock clk 0.40 [all_inputs -not_clocks]
set_output_delay -clock clk 0.40 [all_outputs]
set_max_fanout 16 [current_design]
"""

        return SiliconCircuitDesign(
            module_name=clean_name,
            spec_goal=spec_goal,
            verilog_rtl=rtl,
            testbench_sv=testbench,
            timing_constraints_sdc=sdc,
            sdc_target_freq_mhz=400.0,
            estimated_lut_count=None,
            is_synthesizable=None,
        )


# Global Singleton Silicon Circuit Orchestrator
silicon_circuit_orchestrator = SiliconCircuitOrchestrator()
