name: Solidity Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'smart-contracts/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'smart-contracts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./smart-contracts
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install dependencies
        run: forge install
      - name: Run Forge tests
        run: forge test -vvv
      - name: Check formatting
        run: forge fmt --check
